import { Sparkles, Lightbulb, AlertTriangle } from "lucide-react";
import { AI_GOVERNANCE_SUMMARY } from "@/data/mockGovernanceData";

export default function AiSummary() {
  const { executiveSummary, recommendations } = AI_GOVERNANCE_SUMMARY;

  return (
    <div className="space-y-6">
      {/* Executive Summary Card */}
      <div className="bg-white border border-slate-200 rounded p-6 shadow-xs relative overflow-hidden">
        {/* Subtle decorative gold light flare top right */}
        <div className="absolute top-0 right-0 w-24 h-24 bg-gov-gold-100/30 rounded-full blur-2xl -mr-6 -mt-6"></div>

        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="h-5 w-5 text-gov-gold-500" />
          <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider">
            AI Governance Executive Brief
          </h3>
        </div>

        <p className="text-slate-600 text-sm leading-relaxed font-sans font-medium text-justify">
          {executiveSummary}
        </p>

        <div className="mt-4 flex items-center gap-4 text-xs font-semibold text-slate-500">
          <div className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-red-500"></span>
            <span>1 High Risk Area</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-gov-gold-500"></span>
            <span>2 Medium Risk Areas</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-green-500"></span>
            <span>1 Low Risk Area</span>
          </div>
        </div>
      </div>

      {/* Recommendations Section - Inspired by the lower recommendations in reference image */}
      <div className="bg-white border border-slate-200 rounded shadow-xs overflow-hidden">
        {/* Section Header */}
        <div className="px-6 py-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-gov-gold-50 rounded-full border border-gov-gold-100">
              <Lightbulb className="h-4.5 w-4.5 text-gov-gold-600" />
            </div>
            <div>
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                GOVERNANCE RECOMMENDATIONS
              </h4>
              <p className="text-[10px] font-medium text-slate-400 mt-0.5">
                Automated action items generated by real-time risk assessment models
              </p>
            </div>
          </div>
          <span className="text-[10px] font-mono font-bold bg-gov-navy-950 text-gov-gold-500 border border-gov-navy-900 px-2 py-0.5 rounded tracking-wide uppercase">
            {recommendations.length} Active
          </span>
        </div>

        {/* Horizontal Scroll / Grid of Recommendation Cards */}
        <div className="p-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 bg-slate-50/50">
          {recommendations.map((rec) => {
            const isHigh = rec.risk === "HIGH";
            const isMedium = rec.risk === "MEDIUM";

            let riskBadgeColor = "bg-green-50 text-green-700 border-green-200";
            if (isHigh) riskBadgeColor = "bg-red-50 text-red-700 border-red-200";
            else if (isMedium) riskBadgeColor = "bg-amber-50 text-amber-700 border-amber-200";

            return (
              <div
                key={rec.id}
                className="bg-white border border-slate-200 rounded p-4 shadow-2xs hover:shadow-xs transition-shadow flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between gap-2 mb-3">
                    <span className="text-[11px] font-black text-slate-800 truncate font-mono">
                      {rec.target}
                    </span>
                    <span
                      className={`text-[8px] font-bold px-2 py-0.5 rounded border uppercase tracking-wider ${riskBadgeColor}`}
                    >
                      {rec.risk}
                    </span>
                  </div>
                  <p className="text-slate-600 text-xs font-medium leading-normal mb-4 min-h-[36px]">
                    {rec.recommendation}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-slate-100 text-[10px] text-slate-400">
                  <span className="font-bold uppercase tracking-wider text-[9px] text-slate-400">
                    {rec.category}
                  </span>
                  <span className="font-mono text-slate-300">
                    {rec.id}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
